-- USE shopping;
-- select * from shopping_data; 
-- Q1  how many revenue generated by male customer and female customer --   
-- SELECT 
--     gender,
--     SUM(purchase_amount) AS total_revenue
-- FROM shopping_data
-- GROUP BY gender;
 -- Q2 which customer used a discount but still spend more than average purchase amount -- 
-- FROM shopping_data
-- WHERE discount_applied = 'Yes'
-- AND purchase_amount > (
--     SELECT AVG(purchase_amount)
--     FROM shopping_data

-- );

-- show me top 5 product which have hiesast average ratting IT SHOW IT WILL SELL AT HIGH PRICE ALSO --  
-- SELECT item_purchased, AVG(review_rating) AS "avg_review"
-- FROM shopping_data
-- GROUP BY item_purchased
-- ORDER BY avg_review DESC
-- LIMIT 5;



-- Q4 compare the average purchase amount between Express and Standard shipping -- 
-- SELECT shipping_type, AVG(purchase_amount) AS avg_purchase
-- FROM shopping_data
-- WHERE shipping_type IN ('Express', 'Standard')
-- GROUP BY shipping_type;


  -- Q 5 DO subscribe customer spend more? compare avarage spend and total revenue betwween subscribe and non_subscribe.--  
-- SELECT 
--     subscription_status,
--     count(customer_id) as customer,
--     AVG(purchase_amount) AS average_spend,
--     SUM(purchase_amount) AS total_revenue
-- FROM shopping_data
-- GROUP BY subscription_status;




-- Q 6 WHICH 5 PRODUCT PURCHASES HIGHEST PERCENTAGE OF PURCHASES WITH DISCOUNT APPLIED /--
-- SELECT 
--     item_purchased,
--     COUNT(*) AS total_purchases,
--     SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discount_purchases,
--     (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS discount_percentage
-- FROM shopping_data
-- GROUP BY item_purchased
-- ORDER BY discount_percentage DESC
-- LIMIT 5;

-- Q7 SEGMENT CUSTOMER INTO NEW ,RETURNING,AND LOYAL BASED ON THERE TOTAL NUMBER OF PREVIOUS PURCHASES ,AND SHOW THE COUNT OF EACH SEGMENTS .--


 
-- WITH customer_type AS (
--     SELECT 
--         customer_id,
--         previous_purchases,
--         CASE
--             WHEN previous_purchases = 1 THEN 'new'
--             WHEN previous_purchases BETWEEN 2 AND 10 THEN 'returning'
--             ELSE 'loyal'
--         END AS customer_segment
--     FROM shopping_data
-- )

-- SELECT 
--     customer_segment,
--     COUNT(*) AS number_of_customers
-- FROM customer_type
-- GROUP BY customer_segment;


--  Q8 WHAT ARE THE TOP 3 PRODUCT OF EACH CATEGORY --

-- WITH ranked_products AS (
--     SELECT 
--         category,
--         item_purchased,
--         COUNT(*) AS total_purchases,
--         ROW_NUMBER() OVER (
--             PARTITION BY category 
--             ORDER BY COUNT(*) DESC
--         ) AS rank_num
--     FROM shopping_data
--     GROUP BY category, item_purchased
-- )

-- SELECT category, item_purchased, total_purchases
-- FROM ranked_products
-- WHERE rank_num <= 3;


-- Q9 A CUSTOMERS WHO ARE REPEATE BUYERS (MORE TRHAN 5 PREVIOUS PURCHASE) ALSO LIKELY TO SUBSCRIBE --  

    --  SELECT 
--     subscription_status,
--     COUNT(*) AS total_customers
-- FROM shopping_data
-- WHERE previous_purchases > 5
-- GROUP BY subscription_status;


-- WHAT IS THE REVENUE CONTRIBUTION OF AGE_GROUP --  


-- SELECT 
--     age_group,
--     SUM(purchase_amount) AS total_revenue
-- FROM shopping_data
-- GROUP BY age_group
-- ORDER BY total_revenue DESC;

use  shopping;



